server:
  port: 8081

spring:
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

  datasource:
    username: ****
    password: *********
    url: jdbc:mysql://****************
    driver-class-name: com.mysql.cj.jdbc.Driver

