server:
  port: 8081

spring:
  datasource:
    username: root
    password: tzy20000712
    url: jdbc:mysql://cdb-7baisrai.bj.tencentcdb.com:10225/ework
    driver-class-name: com.mysql.cj.jdbc.Driver

