server:
  port: 8081

spring:
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb

  datasource:
    username: root
    password: tzy20000712
    url: jdbc:mysql://cdb-7baisrai.bj.tencentcdb.com:10225/ework?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver

